### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mocisly** [AnthonyK213/Naivis#2]
Hello, when I compiled Naivis, I found that this file ITopoDS.cpp reported an error. Since it was automatically generated, I don’t know how to modify it, but when I commented it, it can run.
![微信图片_20240402071437](https://github.com/AnthonyK213/Naivis/assets/78899619/a54fa13f-7628-400e-9ad2-80073960988a)
![微信图片_20240402071920](https://github.com/AnthonyK213/Naivis/assets/78899619/4e4ca693-7f9c-4d82-a50a-0cdcf2ffa17f)

**Comment by AnthonyK213** [comment]
It seems that the binder did not handle the overloading properly. what's the version of libclang and occt?

**Comment by mocisly** [comment]
libclang 18.1.2 and occt 7.7.0

**Comment by AnthonyK213** [comment]
Weird. i can't reproduce it, overloading works fine with the deps you provided. Could you post the generated files in `build/binder-gen`?

**Comment by mocisly** [comment]
I just started using the officially compiled occt and got an error. I recompiled occt myself and there were indeed no errors. Thank you very much. Now it runs perfectly.

**Comment by mocisly** [comment]
I just started using the officially compiled occt and got an error. I recompiled occt myself and there was indeed no error. Thank you very much. Now it runs perfectly.
